[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm"]

[phases.install]
cmd = "pnpm install --no-frozen-lockfile --prefer-offline"

[phases.build]
cmd = "pnpm run build"

[start]
cmd = "pnpm start"

[providers.node]
pnpmVersion = "8.15.0"